### ISSUE TITLE
problem with DNS resolution?

### ISSUE THREAD

**Issue by fjramirez1987** [Sebclem/hassio-nextcloud-backup#43] opened 2021-01-14 16:25 UTC
I have a problem that is difficult to explain. I'll try.

My AX3600 router modified to use it as a neutral router does not have nat loopback active. As a consequence, my PC does not resolve my Home Assistant dns (xxxx.duckdns.org) well within my local LAN.

To solve this problem I have installed a DNS server addon Dnsmasq and configured the IP address of the server on each of my computers.

I have a Nextcloud server locally with a DNS nextcloud.xxx.duckdns.org that I can access correctly from inside (thanks to Dnsmasq) and from the Internet.

I have configured the Nextcloud Backup addons with the hostname: 192.168.1.118:8080 (local address of my Nextcloud server). It connects correctly.

I've done a manual backup but it never uploads.

I think it is due to a problem with the DNS resolution. My Nextcloud server resolves the IP address 192.168.1.118:8080 to nextcloud.xxx.duckdns.org. The Nextcloud Backup addon works with the nextcloud.xxx.duckdns.org dns and my router is not able to solve it.

I have solved this problem with some services that I have in my Docker, setting the IP of the DNS servers in the container. With the Home assistant addos I don't know how to do it.

I don't know if I have explained my problem correctly.

This is my log:

[2021-01-14 16:36:57] [info]: 	Satus : Go !
[2021-01-14 16:36:57] [info]: 	Initializing and checking webdav client...
[2021-01-14 16:36:57] [info]: 	Starting auto clean cron...
[2021-01-14 16:36:57] [info]: 	Starting Cron...
[2021-01-14 16:36:58] [info]: 	Hassio API : Go !
[2021-01-14 16:36:58] [info]: 	Nextcloud connection : Go !
[2021-01-14 16:38:29] [info]: 	Creating new snapshot...
[2021-01-14 16:59:14] [info]: 	Snapshot created with id 05467eb3
[2021-01-14 16:59:14] [info]: 	Downloading snapshot 05467eb3...
[2021-01-14 17:01:54] [info]: 	Download success !
[2021-01-14 17:01:54] [info]: 	Uploading snap...
(node:376) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rejectUnauthorized' of undefined
    at /opt/nextcloud_backup/tools/webdavTools.js:231:68
    at new Promise (<anonymous>)
    at WebdavTools._startUpload (/opt/nextcloud_backup/tools/webdavTools.js:208:16)
    at /opt/nextcloud_backup/tools/webdavTools.js:203:22
    at new Promise (<anonymous>)
    at WebdavTools.uploadFile (/opt/nextcloud_backup/tools/webdavTools.js:193:16)
    at /opt/nextcloud_backup/routes/api.js:160:36
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Sebclem** [comment] 2021-01-14 17:43
Hi,
Well the issue you have in logs is not caused by your DNS, but by me being an idiot 😅
It's bug that I have missed during test.
Fix released with version 0.14.1, let me know if this fix your issue

**Comment by fjramirez1987** [comment] 2021-01-14 18:54
ooh.  I have taken longer to explain than you to correct the error.  Everything coincided with the change of my router. 

 Now everything works fine.  Nice job.

**Closed** 2021-01-14 18:54 UTC
Labels: bug
