### ISSUE TITLE
Local backup note auto cleaning

### ISSUE THREAD

**Issue by AryehGielchinsky** [Sebclem/hassio-nextcloud-backup#110] opened 2022-02-10 20:26 UTC
**Describe the bug**
Auto clean does not discard local snapshots after reaching the auto clean limit (5). Auto clean does work correctly on snapshots backed up to Nextcloud.

**To Reproduce**
Install and turn on auto clean (set to 5 snapshots).

**Expected behavior**
I expect autoclean to only retain the last 5 snapshots. 

**System information**
- Home Assistant Version : 2022.2.5
- Home Assistant Supervisor Version : supervisor-2022.01.1
- Nextcloud Version : 22.2.3 (Ubuntu snap)
- Addon version : 0.16.5 
- If any, reverse proxy in fort on Nextcloud : none

**Additional context** 
- I previously had some DNS issues with HA OS, but they've been solved.
- The "Clean Now" button doesn't seem to do anything.
- Thanks for making this addon!

**Addon Logs**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-run: applying... 
[fix-attrs.d] 10-run: exited 1.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Nextcloud Backup
 Easily backup your Home Assistant snapshots to Nextcloud
-----------------------------------------------------------
 Add-on version: 0.16.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.2.3
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:05:08] INFO: Starting Node...
> nexcloud-backup@0.8.0 start
> node ./bin/www
[2022-02-08 08:05:17] [info]: 	Satus : Go !
[2022-02-08 08:05:17] [info]: 	Initializing and checking webdav client...
[2022-02-08 08:05:17] [info]: 	Starting auto clean cron...
[2022-02-08 08:05:17] [info]: 	Starting Cron...
[2022-02-08 08:05:17] [info]: 	Hassio API : Go !
[2022-02-08 08:05:19] [info]: 	Nextcloud connection : Go !
[2022-02-09 00:00:00] [info]: 	Stopping addons...
[2022-02-09 00:00:00] [info]: 	... Ok
[2022-02-09 00:00:00] [info]: 	Creating new snapshot...
[2022-02-09 00:00:49] [info]: 	Snapshot created with id bae297ce
[2022-02-09 00:00:49] [info]: 	Downloading snapshot bae297ce...
[2022-02-09 00:00:51] [info]: 	Download success !
[2022-02-09 00:00:51] [info]: 	Uploading snap...
[2022-02-09 00:00:58] [info]: 	Upload done...
[2022-02-09 00:00:59] [info]: 	...Upload finish ! (status: 201)
[2022-02-09 00:00:59] [info]: 	Starting addons...
[2022-02-09 00:00:59] [info]: 	... Ok
(node:346) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2022-02-09 00:00:59] [info]: 	Cloud clean done.
(node:346) UnhandledPromiseRejectionWarning: undefined
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
[2022-02-09 01:00:01] [info]: 	Cloud clean done.
[2022-02-09 20:20:32] [info]: 	Cloud clean done.
(node:346) UnhandledPromiseRejectionWarning: undefined
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
[2022-02-10 00:00:00] [info]: 	Stopping addons...
[2022-02-10 00:00:00] [info]: 	... Ok
[2022-02-10 00:00:00] [info]: 	Creating new snapshot...
[2022-02-10 00:03:32] [info]: 	Snapshot created with id 4f67eb73
[2022-02-10 00:03:32] [info]: 	Downloading snapshot 4f67eb73...
[2022-02-10 00:03:35] [info]: 	Download success !
[2022-02-10 00:03:35] [info]: 	Uploading snap...
[2022-02-10 00:03:50] [info]: 	Upload done...
[2022-02-10 00:03:50] [info]: 	...Upload finish ! (status: 201)
[2022-02-10 00:03:50] [info]: 	Starting addons...
[2022-02-10 00:03:50] [info]: 	... Ok
(node:346) UnhandledPromiseRejectionWarning: undefined
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
[2022-02-10 00:03:51] [info]: 	Cloud clean done.
(node:346) UnhandledPromiseRejectionWarning: undefined
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
[2022-02-10 01:00:01] [info]: 	Cloud clean done.
```
**Supervisor logs:**
```
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-02-10 22:04:19 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-02-10 22:04:20 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:04:25 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:04:30 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:04:35 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:04:40 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:04:45 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:04:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:04:55 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:05 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:13 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-02-10 22:05:16 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:20 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:25 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:30 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:35 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:40 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:45 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:48 INFO (MainThread) [supervisor.api.middleware.security] /addons access from 229cc4d7_nextcloud_backup
22-02-10 22:05:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:05:55 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:05 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:15 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:20 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:25 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:30 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:35 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-02-10 22:06:35 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:40 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:45 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:06:55 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:07:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:07:05 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:22:40 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:22:45 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:22:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:22:56 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:02 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer
22-02-10 22:23:13 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:18 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:23 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:28 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:33 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:38 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:44 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:23:55 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:00 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:05 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:15 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:20 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:26 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:31 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:36 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected
22-02-10 22:24:41 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:46 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected
22-02-10 22:24:51 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:24:57 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:02 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:08 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:13 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:19 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:25 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:31 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:36 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:41 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:46 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:51 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:25:57 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:03 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:08 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:13 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:19 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:24 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:30 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:35 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:40 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:46 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:52 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:26:57 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:27:03 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
22-02-10 22:27:09 INFO (MainThread) [supervisor.api.middleware.security] /backups access from 229cc4d7_nextcloud_backup
```

![backupsettings](https://user-images.githubusercontent.com/36816882/153490760-83b2acf8-f591-4e68-af83-70e8213fd423.jpg)
![nextcloudbackup](https://user-images.githubusercontent.com/36816882/153490771-5d5c9f1d-aadc-4065-9c77-5f0a7d6b3e51.jpg)

**Comment by Sebclem** [comment] 2022-02-10 20:46
I have the same issue (didn't notice it before), I will check this tomorrow and push a fix as soon as possible (probably tomorrow morning)

**Comment by Sebclem** [comment] 2022-02-11 10:58
This should be fixed with the new release ! 
Feel free to re-open this issue is the issue is still present.

**Closed by Sebclem** 2022-02-11 10:58 UTC
Labels: bug
